---

- name: GROUP | Add groups to the system
  group: >
    name={{ item.name }}
    system={{ item.system | default('no') }}
  with_items:
    - "{{ rpi_groups }}"
  when: item.state is not defined or item.state == 'present'

- name: USER | Add users to the system
  user: >
    name=pi
    shell=/bin/bash
    groups={{ rpi_user_groups | default('') }}
    home=/home/pi
    createhome=yes
    password={{ password | password_hash('sha512') }}
  register: u

- name: AUTHORIZED_KEY | Install SSH public key to pi user
  authorized_key: user=pi key="{{ rpi_ssh_pubkey }}"
  when: rpi_ssh_pubkey is defined

- name: TEMPLATE | Create sudoers file
  template: >
    src=etc/sudoers.d/ansible.j2
    dest=/etc/sudoers.d/ansible
    mode=0440
    validate='visudo -cf %s'
  when: u.changed